[global]
debug = true

[server]
allowed_upload_mimetypes = ['video/webm']
files_path = "files"
log_path = "logs/server.log"
output_path = "files/output"
output_video_extension = "mp4"
port = 3000
static_path = "dist"
target_path = "files/target"
upload_video_extension = "webm"
upload_path = "files/uploads"

[app]
default_screen = 'index'
default_step = "splash"
output_endpoint = "/output"
process_endpoint = "/process"
recording_time = 30
screens = ['index', 'log', 'recorder', 'viewer']
server = "http://localhost:3000"
sounds = ["beep", "bla", "click", "jump", "music", "robot", "transform", "woopwoop", "wrong"]
steps = [
    "splash", "explain", "choosevideo", "choosescript", "chooseconfirm", "record", "replay",
    "swap", "done"
]
upload_endpoint = "/upload"

[app.cam]
width = 1280
height = 720

[errors]
invalid_mimetype = ["415", "Invalid mimetype"]
video_not_found = ["404", "Video with ID not found"]

[[target]]
id = "1"
name = "Laura Lee"

[[target]]
id = "2"
name = "Kim Kardashian"

[[target]]
id = "3"
name = "Mark Zuckerberg"

[[target]]
id = "4"
name = "Logan Paul"

[[target]]
id = "5"
name = "Dotan"

[[target]]
id = "6"
name = "James Charles"

[[target]]
id = "7"
name = "Logan Paul (SD)"

[[target]]
id = "1b"
name = "Laura Lee (kort)"

[[script]]
name = "Klimaat"
text = """
Ik schaam me diep. Het is niet alsof ik me er niet mee bezig houd, ik eet heus niet elke dag vlees en ik heb zo’n meeneem beker voor mijn koffie in de trein. Laatst heb ik zelfs zo’n zakje gekocht voor de broodjes in de supermarkt zodat ik geen plastic meer hoef te gebruiken. Maar ik wil zo graag licht gebruind aan de rand van een infinity pool zitten, met een smoothiebowl met sterfruit en chiazaad in m’n hand, en daarvoor moet ik gewoon naar Bali. En om naar Bali te komen moet ik nou eenmaal vliegen. Voor de goede orde, ik heb wel dat vakje aangevinkt om mij CO2 uitstoot te neutraliseren, dus dan zijn we cool. Toch? Lief klimaat? Toch?"""

[[script]]
name = "Mam"
text = """
Ik kom niet genoeg langs
Het is Vaker bellen, ik heb het gewoon heel druk. """

[[script]]
name = "Nederland"
text = """
Ik heb niet gestemd bij de waterschapsverkiezingen. Ik heb niet eens opgezocht wat waterschap precies is, terwijl ik wel altijd roep dat iedereen gebruik moet maken van zijn democratische recht. Maar het klonk zo onbelangrijk omdat het me alleen maar deed denken aan Waterschapsheuvel wat vooral over zielige konijntjes ging. """

[[script]]
name = "Geghost"
text = """
Ik denk dat het komt omdat ik appen niet echt zie als chatten maar meer als mailen, dus dan beslis ik later wel of ik antwoord. En dat doe ik dan alsnog niet omdat het toch appen is, en ons gesprek dan onderin de lijst raakt, onder de gesprekken die ik wel voer en de mensen waar ik wel op reageer. Omdat ik daar dan wel zin in heb, en in jou eigenlijk niet, want je appt altijd precies op het verkeerde moment. En op een heel irritante manier. Je hoeft niet te eindigen met groetjes. Maar het ligt niet aan jou, echt niet, het ligt aan mij, ik zal beter m’n best doen. Morgen. Want dan stuur ik je wat terug, beloofd."""

[[script]]
name = "Plant"
text = """
Sorry dat je dood bent. Ik had het moeten zien aankomen, je verslapte wat en stilletjes als je bent, heb ik niet op tijd gemerkt dat je me nodig had. Terwijl dat wel de afspraak was, ik haalde jou in huis en zou voor je zorgen. Je af en toe wat bemesten, je wat natspuiten, en vooral veel bewonderen. En juist daarom is het zo schandelijk, ik heb je bruin wordende randjes, je hangende blaadjes, je droge aarde niet gezien, je stille schreeuw om aandacht niet gehoord. Totdat het te laat was. Of misschien niet, ik giet voor de zekerheid nu dan maar een absurde hoeveelheid water in je pot, waar hoogstwaarschijnlijk alleen nog maar je wortels van gaan rotten, maar dan heb ik in elk geval het gevoel dat ik heb gedaan wat ik kon. En kan ik met een gerust hart zaterdag weer naar de Intratuin. """